version: "3.4"

services:
  # Postgres for drone service.
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: drone_db
      POSTGRES_PASSWORD: drone_pwd
      POSTGRES_USER: drone_user
    volumes:
      - drone-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  drone-postgres-data:
    driver: local
