version: '3.4'

services:
  drone-service:
    image: 'docker-spring-boot-postgres:latest'
#    platform: linux/x86_64
    build:
      context: .
    environment:
      SPRING_PROFILE: dev
      POSTGRES_DB: drone_db
      POSTGRES_PASSWORD: drone_pwd
      POSTGRES_USER: drone_user
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DB_NAME: drone_db
    ports:
      - "8080:8080"
    networks:
      - drones_net
    depends_on:
      - postgres

  # Postgres for drone service.
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: drone_db
      POSTGRES_PASSWORD: drone_pwd
      POSTGRES_USER: drone_user
    volumes:
      - drone-postgres-data:/var/lib/postgresql/data
    networks:
      - drones_net
    ports:
      - "5432:5432"

volumes:
  drone-postgres-data:
    driver: local
networks:
  drones_net:
    driver: bridge
